"""Initial migration

Revision ID: 76a4075baba6
Revises: 
Create Date: 2025-09-19 02:04:05.346942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a4075baba6'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('patronymic', sa.String(length=30), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_index('ix_unique_user_tg_id', 'users', ['tg_id'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('media_link', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('is_publish_now', sa.Boolean(), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_checked', 'posts', ['is_checked'], unique=False)
    op.create_index('ix_posts_checked_published', 'posts', ['is_checked', 'is_published'], unique=False)
    op.create_index('ix_posts_paid', 'posts', ['is_paid'], unique=False)
    op.create_index('ix_posts_publish_date', 'posts', ['publish_date'], unique=False)
    op.create_index('ix_posts_published', 'posts', ['is_published'], unique=False)
    op.create_index('ix_posts_sender_checked', 'posts', ['sender_id', 'is_checked'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_sender_checked', table_name='posts')
    op.drop_index('ix_posts_published', table_name='posts')
    op.drop_index('ix_posts_publish_date', table_name='posts')
    op.drop_index('ix_posts_paid', table_name='posts')
    op.drop_index('ix_posts_checked_published', table_name='posts')
    op.drop_index('ix_posts_checked', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_unique_user_tg_id', table_name='users')
    op.drop_table('users')
    op.drop_table('prices')
    # ### end Alembic commands ###
